
CREATE TABLE IF NOT EXISTS posts (
     id INT PRIMARY KEY NOT NULL,
     userId INT NOT NULL,
     title VARCHAR(255) NOT NULL,
     body VARCHAR(1000) NOT NULL
     -- FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
